name: destop

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends libglfw3 libglfw3-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev
          mkdir ${{ env.PROJECT_RELEASE_PATH }}
          ls
        shell: bash

      # - name: configure
      #   run: ./configure
      # - name: make check
      #   run: make check
      # - name: make distcheck
      #   run: make distcheck
      - name: Setup Emscripten toolchain
        # You may pin to the exact commit or the version.
        # uses: mymindstorm/setup-emsdk@6ab9eb1bda2574c4ddb79809fc9247783eaf9021
        uses: mymindstorm/setup-emsdk@v14
        with:
          # Version to install
          # version:# optional, default is latest
          # If true will not download any version of Emscripten. emsdk will still be added to PATH.
          # no-install:# optional
          # If true will not cache any downloads with tc.cacheDir.
          no-cache:
            true # optional
            # Directory to cache emsdk in. This folder will go under $GITHUB_HOME (I.e. build dir) and be cached using @actions/cache.
          # actions-cache-folder:# optional, default is
          # Override the cache key. By default, it is `{Github workflow name}-{Emscripten version}-{OS type}-${CPU architecture}`.
          # cache-key:# optional, default is
          # Fetch package information for all the new tools and SDK versions
          update:
            true # optional
            # Deprecated in favor of `update`.
          update-tags: false # optional
      - name: make
        run: make
