name: wasm

on:
  workflow_dispatch:
  push:
    paths:
      - "**"
      - ".github/workflows/wasm.yml"
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      PROJECT_NAME: ${{ github.event.repository.name }}
      PROJECT_BUILD_PATH: ${{ github.workspace }}/build
      PROJECT_RELEASE_PATH: ${{ github.event.repository.name }}_dev_linux_x64
      PROJECT_CUSTOM_FLAGS: ""
      PLATFORM: PLATFORM_WEB

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          path: ${{ env.PROJECT_NAME }}

      - name: Checkout raylib repo
        uses: actions/checkout@v4
        with:
          repository: raysan5/raylib
          path: raylib

      # - name: Setup Release Paths
      #   run: |
      #     echo "PROJECT_RELEASE_PATH=${{ env.PROJECT_NAME }}_v${{ github.event.release.tag_name }}_linux_x64" >> $GITHUB_ENV
      #   shell: bash
      #   if: github.event_name == 'release' && github.event.action == 'published'

      - name: Setup Environment
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends libglfw3 libglfw3-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev
          # mkdir ${{ env.PROJECT_RELEASE_PATH }}
          # ls
        shell: bash

      # - name: Setup Emscripten toolchain
      #   # You may pin to the exact commit or the version.
      #   # uses: mymindstorm/setup-emsdk@6ab9eb1bda2574c4ddb79809fc9247783eaf9021
      #   uses: mymindstorm/setup-emsdk@v14
      #   with:
      #     no-cache: true
      #     update: true
      #     update-tags: false

      - name: Install Emscripten
        run: |
          mkdir -p ${{ env.PROJECT_BUILD_PATH }}
          cd ${{ env.PROJECT_BUILD_PATH }}
          git clone https://github.com/emscripten-core/emsdk.git ${{ env.PROJECT_BUILD_PATH }}/emsdk
          cd ${{ env.PROJECT_BUILD_PATH }}/emsdk
          echo "pwd $(pwd)"
          echo "ls $(ls)"
          ./emsdk install latest
          ./emsdk activate latest
          source ${{ env.PROJECT_BUILD_PATH }}/emsdk/emsdk_env.sh
          emcc --version
        shell: bash

      # - name: Build raylib Library
      #   run: |
      #     cd raylib/src
      #     gcc --version
      #     make PLATFORM=${{ env.PLATFORM }} BUILD_MODE=RELEASE RAYLIB_LIBTYPE=STATIC RAYLIB_PROJECT_RELEASE_PATH=. -B

      - name: Build Project
        run: |
          echo "pwd $(pwd)"
          echo "ls $(ls)"
          make PLATFORM=${{ env.PLATFORM }}

      # - name: Generate Artifacts
      #   run: |
      #     ls ${{ env.PROJECT_BUILD_PATH }}
      #     cp ${{ env.PROJECT_BUILD_PATH }}/${{ env.PROJECT_NAME }} ${{ env.PROJECT_RELEASE_PATH }}
      #     cp ${{ env.PROJECT_NAME }}/README.md ${{ env.PROJECT_RELEASE_PATH }}
      #     cp ${{ env.PROJECT_NAME }}/LICENSE ${{ env.PROJECT_RELEASE_PATH }}
      #     ls ${{ env.PROJECT_RELEASE_PATH }}
      #     7z a ./${{ env.PROJECT_RELEASE_PATH }}.zip ./${{ env.PROJECT_RELEASE_PATH }}

      # Issue: Double zip: https://github.com/actions/upload-artifact/issues/39
      # - name: Upload Artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: ${{ env.PROJECT_RELEASE_PATH }}.zip
      #     path: ./${{ env.PROJECT_RELEASE_PATH }}.zip

      # Alternative: https://github.com/marketplace/actions/gh-release
      # - name: Upload Artifact to Release
      #   uses: actions/upload-release-asset@v1.0.1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ github.event.release.upload_url }}
      #     asset_name: ${{ env.PROJECT_RELEASE_PATH }}.zip
      #     asset_path: ./${{ env.PROJECT_RELEASE_PATH }}.zip
      #     asset_content_type: application/zip
      #   if: github.event_name == 'release' && github.event.action == 'published'
